### ISSUE TITLE
two (dose-response) data sets to be added

### ISSUE THREAD

**Issue by christianroever** [wviechtb/metadat#24]
[doseresponsedata.zip](https://github.com/wviechtb/metadat/files/10176589/doseresponsedata.zip)

attached are the relevant files for the two data sets.
Thanks!

Christian

**Comment by wviechtb** [comment]
Great, thanks for this contribution! Will add them to the package. Would you maybe want to suggest some proposed analyses for the two examples after the creation of the line plots? I can imagine that some may be interested in seeing how one could analyze these, for example using a logistic mixed-effects model. Given the low counts, maybe a Bayesian approach would also be interesting.

**Comment by christianroever** [comment]
Hi Wolfgang,

that is a good point, however, our idea was to use these data sets as
examples to showcase an analysis, whose details are still to be figured
out to some degree. We first wanted to nail down the data, I'd suggest
we can expand on the example R code once we have the example and code
all worked out.

Cheers,

Christian

**Comment by wviechtb** [comment]
Sure, can always add this later!

**Comment by wviechtb** [comment]
The two datasets have been added. Thanks again for this contribution!
