### ISSUE TITLE
Add dat.barone2019

### ISSUE THREAD

**Issue by kylehamilton** [wviechtb/metadat#3]
This meta-analysis has a nice example of publication bias see funnel plot from paper. Authors have included data and code on OSF so adding to metadat should be pretty straight forward. I'll try to make a pull request with the data sometime this week. But just in case the semester gets me I wanted to make sure there was a record of it here.

Citation
Barone, P., Corradi, G., & Gomila, A. (2019). Infants’ performance in spontaneous-response false belief tasks: A review and meta-analysis. Infant Behavior and Development, 57, 101350. https://doi.org/10.1016/j.infbeh.2019.101350

OSF
https://osf.io/re8uj/?view_only=d2605771dd664831a104318db9ff7aa9

![image](https://user-images.githubusercontent.com/2274317/63859275-e7392680-c95b-11e9-91cf-b2d6826b95ef.png)
Fig. 3

**Comment by wviechtb** [comment]
Thanks for the suggestion. Would make a nice addition to the package!
