### ISSUE TITLE
Warning on build with dat.ho2012 unknown macro '\italic 

### ISSUE THREAD

**Issue by kylehamilton** [wviechtb/metadat#4]
When installing metadat the system throws a warning about the \italic I'll submit a patch in a second that fixes this. 

==> Rcmd.exe INSTALL --no-multiarch --with-keep.source metadat

* installing to library 'C:/Users/Kyle Hamilton/Documents/R/win-library/3.6'
* installing *source* package 'metadat' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
Warning: C:/Users/Kyle Hamilton/Documents/GitHub/metadat/man/dat.ho2012.Rd:10: unknown macro '\italic'
Warning: C:/Users/Kyle Hamilton/Documents/GitHub/metadat/man/dat.ho2012.Rd:11: unknown macro '\italic'
Warning: C:/Users/Kyle Hamilton/Documents/GitHub/metadat/man/dat.ho2012.Rd:15: unknown macro '\italic'

**Comment by wviechtb** [comment]
Right, there is no such text markup command (https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Marking-text).
