### ISSUE TITLE
Data sets require additional information

### ISSUE THREAD

**Issue by kylehamilton** [wviechtb/metadat#6]
The documentation for dat.besson2016 is not complete.

**Comment by kylehamilton** [comment]
The documentation for dat.cleasby2012 is not complete.

**Comment by kylehamilton** [comment]
The documentation for dat.maire2019 is not complete.

**Comment by kylehamilton** [comment]
The documentation for dat.weaver2018 is not complete.

**Comment by kylehamilton** [comment]
The documentation for dat.valstad2017 is not complete.

**Comment by wviechtb** [comment]
Yeah, still lots of work to do! Thanks for making this list.

**Comment by wviechtb** [comment]
I am going to close this issue and have opened up a new issue where the datasets that need to be added/completed are listed under issue #15.
